name: libclang
description: Dart FFI bindings to libclang that provides the ability to analyze C/C++ code.
homepage: https://github.com/ctrysbita/libclang-dart
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies: {}
